# Generated by Django 3.2 on 2023-03-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('SellerId', models.AutoField(primary_key=True, serialize=False)),
                ('SellerName', models.CharField(max_length=100)),
                ('mobileNo', models.CharField(max_length=20)),
                ('Addr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=100)),
                ('mobileNo', models.CharField(max_length=20)),
            ],
        ),
    ]
