# Generated by Django 3.2 on 2023-03-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='Addr',
            new_name='password',
        ),
        migrations.AddField(
            model_name='seller',
            name='SellerEmail',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
