# Generated by Django 3.2 on 2023-03-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_seller_sellerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='SellerId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
