# Generated by Django 3.2 on 2023-03-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_seller_sellerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='role',
            field=models.CharField(choices=[('seller', 'Seller'), ('user', 'User')], default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('seller', 'Seller'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
