# Generated by Django 3.2 on 2023-04-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='UserEmail',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='user', max_length=100),
        ),
        migrations.AlterField(
            model_name='seller',
            name='role',
            field=models.CharField(choices=[('seller', 'Seller'), ('user', 'User')], default='seller', max_length=20),
        ),
    ]
