# Generated by Django 3.2 on 2023-04-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='productId',
            field=models.IntegerField(default=1),
        ),
    ]
