# Generated by Django 3.2 on 2023-04-14 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_cart_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='userId',
            new_name='user_id',
        ),
    ]
