# Generated by Django 3.2 on 2023-04-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_rename_userid_cart_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productId',
            field=models.IntegerField(default=1),
        ),
    ]
