# Generated by Django 3.2 on 2023-04-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_product_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='image',
            field=models.TextField(),
        ),
    ]
